version: "3.9"

services:
  database:
    image: postgres
    restart: always
    environment:
      TZ: Asia/Seoul
      POSTGRES_PASSWORD: auth1234!
      POSTGRES_USER: study
      POSTGRES_DB: authentication
      POSTGRES_INITDB_ARGS: --encoding=UTF-8 --data-checksums
    ports:
      - "5432:5432"